### ISSUE TITLE
Lighthouse not working anymore

### ISSUE THREAD

**Issue by hjelmdal** [gsoft-inc/azure-pipelines-lighthouse#16]
As of december 18th, my release pipeline has failed with a -Lighthouse v7.0 message of bad configuration flags being set. My CLI config is clean, so I am guessing that the extension is injecting something not supported anymore?

```
2020-12-29T10:36:58.6440336Z Executing Lighthouse...
2020-12-29T10:36:58.6457141Z [command]/usr/local/bin/node /home/vsts/work/_temp/__lighthouse/node_modules/lighthouse/lighthouse-cli/index.js https://myurl.com --emulated-form-factor=none --throttling-method=provided --verbose --output=html --output=json --output-path=/home/vsts/work/_temp/__lighthouse/myurl.com-93037 --chrome-flags=--headless
2020-12-29T10:36:59.3494745Z Tue, 29 Dec 2020 10:36:59 GMT ChromeLauncher:verbose created /tmp/lighthouse.zCazdDh
2020-12-29T10:36:59.3520310Z Tue, 29 Dec 2020 10:36:59 GMT ChromeLauncher:verbose Launching with command:
2020-12-29T10:36:59.3522884Z "/usr/bin/google-chrome-stable" --disable-features=TranslateUI --disable-extensions --disable-component-extensions-with-background-pages --disable-background-networking --disable-sync --metrics-recording-only --disable-default-apps --mute-audio --no-default-browser-check --no-first-run --disable-backgrounding-occluded-windows --disable-renderer-backgrounding --disable-background-timer-throttling --force-fieldtrials=*BackgroundTracing/default/ --remote-debugging-port=33441 --disable-setuid-sandbox --user-data-dir=/tmp/lighthouse.zCazdDh --headless --enable-features=AutofillShowTypePredictions about:blank
2020-12-29T10:36:59.3568394Z Tue, 29 Dec 2020 10:36:59 GMT ChromeLauncher:verbose Chrome running with pid 2605 on port 33441.
2020-12-29T10:36:59.3572842Z Tue, 29 Dec 2020 10:36:59 GMT ChromeLauncher Waiting for browser.
2020-12-29T10:36:59.3573241Z Tue, 29 Dec 2020 10:36:59 GMT ChromeLauncher Waiting for browser...
2020-12-29T10:36:59.8661231Z Tue, 29 Dec 2020 10:36:59 GMT ChromeLauncher Waiting for browser.....
2020-12-29T10:37:00.3684646Z Tue, 29 Dec 2020 10:37:00 GMT ChromeLauncher Waiting for browser.......
2020-12-29T10:37:00.3702591Z Tue, 29 Dec 2020 10:37:00 GMT ChromeLauncher Waiting for browser.......[32m✓[0m
2020-12-29T10:37:00.3708609Z Tue, 29 Dec 2020 10:37:00 GMT status:verbose Create config
2020-12-29T10:37:00.3753368Z Tue, 29 Dec 2020 10:37:00 GMT ChromeLauncher Killing Chrome instance 2605
2020-12-29T10:37:00.3965976Z Runtime error encountered: Invalid emulation flag. Emulation configuration changed in LH 7.0. See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md
2020-12-29T10:37:00.3967872Z Error: Invalid emulation flag. Emulation configuration changed in LH 7.0. See https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md
2020-12-29T10:37:00.3972572Z     at assertValidFlags (/home/vsts/work/_temp/__lighthouse/node_modules/lighthouse/lighthouse-core/config/config.js:183:11)
2020-12-29T10:37:00.3973696Z     at new Config (/home/vsts/work/_temp/__lighthouse/node_modules/lighthouse/lighthouse-core/config/config.js:382:7)
2020-12-29T10:37:00.3974799Z     at generateConfig (/home/vsts/work/_temp/__lighthouse/node_modules/lighthouse/lighthouse-core/index.js:64:10)
2020-12-29T10:37:00.3975782Z     at lighthouse (/home/vsts/work/_temp/__lighthouse/node_modules/lighthouse/lighthouse-core/index.js:43:18)
2020-12-29T10:37:00.3976995Z     at runLighthouse (/home/vsts/work/_temp/__lighthouse/node_modules/lighthouse/lighthouse-cli/run.js:224:32)
2020-12-29T10:37:00.3977652Z     at processTicksAndRejections (internal/process/task_queues.js:93:5)
2020-12-29T10:37:00.4073576Z 
```

**Comment by asimmon** [comment]
Hi @hjelmdal from the logs I can see that your CLI arguments doesn't seem empty. Looks like you've added:

    --emulated-form-factor=none --throttling-method=provided --verbose

When I look at your logs, [this documentation page is mentioned](https://github.com/GoogleChrome/lighthouse/blob/master/docs/emulation.md). `--emulated-form-factor` have been removed and you muse use `--preset` instead.

It's true that the extension injects other CLI arguments, but as you can see in the logs, it's only those required to generate an HTML and JSON output as well as running the tool in headless mode. I've tested it with Lighthouse 7 and it works well with empty CLI arguments.
